# Generated by Django 3.2.16 on 2024-12-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100, verbose_name='Категория номера')),
                ('rooms', models.PositiveIntegerField(verbose_name='Количество комнат')),
                ('date_in', models.DateField(verbose_name='Дата заезда')),
                ('date_out', models.DateField(verbose_name='Дата выезда')),
                ('date_in_fact', models.DateField(blank=True, null=True, verbose_name='Фактическая дата заезда')),
                ('date_out_fact', models.DateField(blank=True, null=True, verbose_name='Фактическая дата выезда')),
                ('bonus', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-date_in'],
            },
        ),
    ]
